import { describe, expect, it } from "vitest";
import { makeFriction, makeRound1Result, makeRound2Result } from "@/lib/engine/__tests__/fixtures";
import type { BoardroomReport } from "@/lib/engine/types";
import { formatBoardroomReport } from "../markdown-export";

function makeReport(overrides: Partial<BoardroomReport> = {}): BoardroomReport {
  return {
    projectName: "TestApp",
    timestamp: "2025-01-15T10:00:00Z",
    ceoVision: "Build the best product",
    round1: [
      makeRound1Result({ role: "cpo", name: "Vegeta", verdict: "GO" }),
      makeRound1Result({ role: "cmo", name: "Bulma", verdict: "GO_WITH_CHANGES" }),
      makeRound1Result({ role: "cfo", name: "Piccolo", verdict: "VIABLE" }),
      makeRound1Result({ role: "cro", name: "Whis", verdict: "VALIDATED" }),
      makeRound1Result({ role: "cco", name: "Gohan", verdict: "SHIP_IT" }),
      makeRound1Result({ role: "cto", name: "Trunks", verdict: "FEASIBLE" }),
    ],
    frictions: [],
    round2: [],
    synthesis: {
      consensus: ["Vegeta: Launch with freemium model"],
      compromises: [],
      impasses: [],
      collectiveVerdict: "GO",
    },
    totalDurationMs: 12500,
    ...overrides,
  };
}

describe("formatBoardroomReport", () => {
  it("contains header with project name and date", () => {
    const report = makeReport();
    const md = formatBoardroomReport(report);

    expect(md).toContain("# BoardRoom Report — TestApp — 2025-01-15");
  });

  it("shows 6 individual verdicts with name, title, and verdict", () => {
    const report = makeReport();
    const md = formatBoardroomReport(report);

    expect(md).toContain("**Vegeta** (Chief Product Officer): **GO**");
    expect(md).toContain("**Bulma** (Chief Marketing Officer): **GO_WITH_CHANGES**");
    expect(md).toContain("**Piccolo** (Chief Financial Officer): **VIABLE**");
    expect(md).toContain("**Whis** (Chief Research Officer): **VALIDATED**");
    expect(md).toContain("**Gohan** (Chief Creative Officer): **SHIP_IT**");
    expect(md).toContain("**Trunks** (Chief Technology Officer): **FEASIBLE**");
  });

  it("shows collective verdict", () => {
    const report = makeReport();
    const md = formatBoardroomReport(report);

    expect(md).toContain("## Collective Verdict: **GO**");
  });

  it("contains the footer with BoardRoom AI branding", () => {
    const report = makeReport();
    const md = formatBoardroomReport(report);

    expect(md).toContain("Generated by BoardRoom AI");
  });

  it("includes friction section when frictions exist", () => {
    const report = makeReport({
      frictions: [
        makeFriction({
          description: "Vegeta (GO) vs Piccolo (NOT_VIABLE)",
        }),
      ],
    });
    const md = formatBoardroomReport(report);

    expect(md).toContain("## Friction Points");
    expect(md).toContain("Vegeta (GO) vs Piccolo (NOT_VIABLE)");
  });

  it("excludes friction section when no frictions", () => {
    const report = makeReport({ frictions: [] });
    const md = formatBoardroomReport(report);

    expect(md).not.toContain("## Friction Points");
  });

  it("includes round 2 section when round2 results exist", () => {
    const report = makeReport({
      round2: [
        makeRound2Result({
          role: "cpo",
          position: "MAINTAIN",
          argument: "I stand by my analysis.",
        }),
      ],
    });
    const md = formatBoardroomReport(report);

    expect(md).toContain("## Round 2 — Contradictory Debate");
    expect(md).toContain("**MAINTAIN**");
    expect(md).toContain("I stand by my analysis.");
  });

  it("excludes round 2 section when no round2 results", () => {
    const report = makeReport({ round2: [] });
    const md = formatBoardroomReport(report);

    expect(md).not.toContain("## Round 2 — Contradictory Debate");
  });

  it("shows CEO vision section", () => {
    const report = makeReport({ ceoVision: "Disrupt the market" });
    const md = formatBoardroomReport(report);

    expect(md).toContain("## CEO Vision");
    expect(md).toContain("Disrupt the market");
  });

  it("shows duration in footer", () => {
    const report = makeReport({ totalDurationMs: 15000 });
    const md = formatBoardroomReport(report);

    expect(md).toContain("15.0s");
  });
});
