import type { BoardroomReport } from "@boardroom/engine";
import { describe, expect, it } from "vitest";
import {
  makeDebateHistory,
  makeDebateTurn,
  makeFriction,
  makeRound1Result,
} from "@/packages/engine/__tests__/fixtures";
import { formatBoardroomReport } from "../markdown-export";

function makeReport(overrides: Partial<BoardroomReport> = {}): BoardroomReport {
  return {
    projectName: "TestApp",
    timestamp: "2025-01-15T10:00:00Z",
    ceoVision: "Build the best product",
    round1: [
      makeRound1Result({ role: "cpo", name: "Vegeta", verdict: "GO" }),
      makeRound1Result({ role: "cmo", name: "Bulma", verdict: "GO_WITH_CHANGES" }),
      makeRound1Result({ role: "cfo", name: "Piccolo", verdict: "VIABLE" }),
      makeRound1Result({ role: "cro", name: "Whis", verdict: "VALIDATED" }),
      makeRound1Result({ role: "cco", name: "Gohan", verdict: "SHIP_IT" }),
      makeRound1Result({ role: "cto", name: "Trunks", verdict: "FEASIBLE" }),
    ],
    frictions: [],
    synthesis: {
      consensus: ["Vegeta: Launch with freemium model"],
      compromises: [],
      impasses: [],
      collectiveVerdict: "GO",
    },
    totalDurationMs: 12500,
    ...overrides,
  };
}

describe("formatBoardroomReport", () => {
  it("contains header with project name and date", () => {
    const report = makeReport();
    const md = formatBoardroomReport(report);

    expect(md).toContain("# BoardRoom Report — TestApp — 2025-01-15");
  });

  it("shows 6 individual verdicts with name, title, and verdict", () => {
    const report = makeReport();
    const md = formatBoardroomReport(report);

    expect(md).toContain("**Vegeta** (Chief Product Officer): **GO**");
    expect(md).toContain("**Bulma** (Chief Marketing Officer): **GO_WITH_CHANGES**");
    expect(md).toContain("**Piccolo** (Chief Financial Officer): **VIABLE**");
    expect(md).toContain("**Whis** (Chief Research Officer): **VALIDATED**");
    expect(md).toContain("**Gohan** (Chief Creative Officer): **SHIP_IT**");
    expect(md).toContain("**Trunks** (Chief Technology Officer): **FEASIBLE**");
  });

  it("shows collective verdict", () => {
    const report = makeReport();
    const md = formatBoardroomReport(report);

    expect(md).toContain("## Collective Verdict: **GO**");
  });

  it("contains the footer with BoardRoom AI branding", () => {
    const report = makeReport();
    const md = formatBoardroomReport(report);

    expect(md).toContain("Generated by BoardRoom AI");
  });

  it("includes friction section when frictions exist", () => {
    const report = makeReport({
      frictions: [
        makeFriction({
          description: "Vegeta (GO) vs Piccolo (NOT_VIABLE)",
        }),
      ],
    });
    const md = formatBoardroomReport(report);

    expect(md).toContain("## Friction Points");
    expect(md).toContain("Vegeta (GO) vs Piccolo (NOT_VIABLE)");
  });

  it("excludes friction section when no frictions", () => {
    const report = makeReport({ frictions: [] });
    const md = formatBoardroomReport(report);

    expect(md).not.toContain("## Friction Points");
  });

  it("shows CEO vision section", () => {
    const report = makeReport({ ceoVision: "Disrupt the market" });
    const md = formatBoardroomReport(report);

    expect(md).toContain("## CEO Vision");
    expect(md).toContain("Disrupt the market");
  });

  it("shows duration in footer", () => {
    const report = makeReport({ totalDurationMs: 15000 });
    const md = formatBoardroomReport(report);

    expect(md).toContain("15.0s");
  });

  it("includes multi-turn debate section when debates exist", () => {
    const report = makeReport({
      debates: [
        makeDebateHistory({
          friction: makeFriction({ description: "Vegeta vs Piccolo on unit economics" }),
          moderatorOpening: "Let's settle this disagreement.",
          turns: [
            makeDebateTurn({
              speaker: "cpo",
              type: "CHALLENGE",
              content: "The market validates my position.",
              addressedTo: ["cfo"],
              positionShift: "UNCHANGED",
            }),
            makeDebateTurn({
              speaker: "cfo",
              type: "CONCESSION",
              content: "I accept a phased approach.",
              addressedTo: ["cpo"],
              positionShift: "SOFTENED",
            }),
          ],
          outcome: "CONVERGED",
          outcomeSummary: "Both agreed on phased launch.",
        }),
      ],
    });
    const md = formatBoardroomReport(report);

    expect(md).toContain("## Multi-Turn Debate");
    expect(md).toContain("Vegeta vs Piccolo on unit economics");
    expect(md).toContain("Let's settle this disagreement.");
    expect(md).toContain("**Vegeta** [CHALLENGE");
    expect(md).toContain("The market validates my position.");
    expect(md).toContain("**Piccolo** [CONCESSION");
    expect(md).toContain("*Position: SOFTENED*");
    expect(md).toContain("**Resolution:** Both agreed on phased launch.");
  });

  it("excludes debate section when no debates", () => {
    const report = makeReport();
    const md = formatBoardroomReport(report);

    expect(md).not.toContain("## Multi-Turn Debate");
  });
});
